### ISSUE TITLE
brak doładowywania obrazków

### ISSUE THREAD

**Issue by mszymczakowski** [sagittarius89/kerbstone#1]
po zwinięciu kilku elementów nie doładowują się obrazki, np. avatary czy załączniki do wpisów

obstawiam, że na scroll jest jakiś event doładowujący obrazki, ale nie udało mi się na szybko go znaleźć

**Comment by mszymczakowski** [comment]
wystarczy wywołać `$("img.lazy").lazyload();` po każdym zwinięciu lub rozwinięciu elementu

**Comment by sagittarius89** [comment]
Rozwiązane. Pobierz źródła bądź skrzystaj z https://greasyfork.org/pl/scripts/26217-kraw%C4%99%C5%BCnik/
